baseURL: "https://ggp1.github.io/"
title: Gastón Palomeque
theme: profile
pagination:
  pagerSize: 3

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

enableRobotsTXT: true

markup:
  highlight:
    style: onedark
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2

params:
  title: "Gastón Palomeque"
  description: My personal blog
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon.ico"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "auto"

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  color:
    textColor: "#000"
    secondaryTextColor: "#6c757d"
    textLinkColor: "#4d7fb5"
    backgroundColor: "#eaedf0"
    secondaryBackgroundColor: "#64ffda1a"
    primaryColor: "#4d7fb5"
    secondaryColor: "#f8f9fa"
    btnBackgroundColor: "#9cc3ea8f"

    darkmode:
      textColor: "#e4e6eb"
      secondaryTextColor: "#b0b3b8"
      textLinkColor: "#ffffff"
      backgroundColor: "#18191a"
      secondaryBackgroundColor: "#212529"
      primaryColor: "#ffffff"
      secondaryColor: "#212529"
      btnBackgroundColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/favicon.ico" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "" # Brand name for the brand | default is the title variable
    disableSearch: false
    searchPlaceholder: "Search"
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: true
      disableProjects: false
      disableAchievements: true
      disableContact: true

  # Hero
  hero:
    enable: true
    intro: ""
    title: "Gastón Palomeque"
    subtitle: "Software Engineer"
    content: "Creating technology-driven solutions with passion"
    image: /images/avatar.jpg
    bottomImage:
      enable: true
      # image: "/images/competition.png"
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
      customIcons:
        - icon: /images/github.png
          url: https://github.com/GGP1
        - icon: /images/linkedin.png
          url: https://www.linkedin.com/in/gastonpalomeque/
        - icon: /images/stackoverflow.png
          url: https://stackoverflow.com/users/12574067/ggp
        # - icon: /images/nostr.png
        #   url: https://njump.me/

  # About
  about:
    enable: true
    title: "About"
    image: ""
    content: |-
      I'm an autodidact Software Engineer passionate about computer science and economics.
      
      It all started with a simple interest in understanding how computers work, and before I knew it, I was spending hours each day learning new skills and putting them into practice. The journey hasn't stopped there; every day brings something new to explore, and I'm continuously extending my knowledge.

      When I'm not coding, you'll often find me staying active through swimming, running, or playing football or tennis. These activities keep my mind sharp and 
      help me approach challenges with a fresh perspective.

      I'm also deeply interested in economics, particularly in the fundamentals of money, macroeconomics, and human capital allocation behavior. This passion
      informs my decision-making and helps me navigate an ever-changing world.

      Lately, I've been diving deep into the exciting field of artificial intelligence and machine learning. Specifically, I'm exploring techniques to enhance open-source large language models. It's a rapidly evolving field, and I'm eager to share what I learn along the way.
    skills:
      enable: true
      title: "To conclude, here are some of the technologies I'm experienced with:"
      items:
        - Go
        - Python
        - Docker
        - AWS
        - Azure
        - GCP
        - Elasticsearch
        - Typescript
        - PostgreSQL
        - Redis
        - Prometheus
        - Nginx
        - Rust
        - Bash

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Senior Software Engineer"
        company: "Wazuh"
        companyUrl: "https://wazuh.com"
        date: "Mar 2023 - present"
        featuredLink:
          enable: true
          name: "Proof of work"
          url: "https://github.com/wazuh/wazuh/issues?q=assignee%3AGGP1"
        info:
          enable: false
        content: |
          Currently working as a Senior Software Engineer in the Server team, maintaining the APIs, cluster, external integrations and cloud services.

          I am in charge of developing the server and its communications with the agents and indexer nodes for the upcoming 5.0 release.

      - job: "Software Developer"
        company: "Avature"
        companyUrl: "https://avature.com"
        date: "Oct 2021 - Mar 2023"
        featuredLink:
          enable: true
          name: "Visit the site"
          url: "https://avature.com"
        info:
          enable: false
        content: |
          Worked in one of the Core teams, maintaining and improving the main CRM application.

          - Boosted the team's test coverage by 30\% and resolved critical bugs impacting 1.5+ million users.
          - Proposed a best practices guide on the main UI testing tool which was adopted by all the teams in the company.
          - Automated the assignation of code reviews creating a load balancer script that had into account reviewers expertise, vacations and workload.
          - Delivered high-quality solutions for multiple time-sensitive projects while adhering to strict deadlines.
          - Refactored legacy systems to improve performance and maintainability while enhancing technical documentation.

  # Education
  education:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Business Administration"
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievement.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievement.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievement.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Kure
        content: Command-line password manager with a minuscule attack surface and state-of-the-art encryption. First of its kind to offer sessions.
        image: ""
        # featured:
        #   name: Demo
        #   link: demo_url
        badges:
          - Go
          - Cryptography
          - CLI
          - Security
        links:
          - icon: fab fa-github
            url: https://www.github.com/GGP1/kure

      - title: Adak
        content: E-commerce RESTful API server with industry-standard features, supporting both monolithic and microservices architectures.
        image: ""
        # featured:
        #   name: Demo
        #   link: demo_url
        badges:
          - "Go"
          - "Docker"
          - "Microservices"
          - "Redis"
          - "Prometheus"
        links:
          - icon: fab fa-github
            url: https://www.github.com/GGP1/adak

      - title: Groove
        content: Event planning and discovery mobile application.
        image: ""
        # featured:
        #   name: Demo
        #   link: demo_url
        badges:
          - "React"
          - "Typescript"
        links:
          - icon: fab fa-github
            url: https://www.github.com/GGP1/groove
      - title: Btcs
        content: Simplified Bitcoin implementation featuring a simulated peer-to-peer network based on Docker.
        image: ""
        # featured:
        #   name: Demo
        #   link: demo_url
        badges:
          - "Distributed systems"
          - "Peer-to-peer"
          - "Networking"
          - "Blockchain"
          - "Cryptography"
          - "Docker"
        links:
          - icon: fab fa-github
            url: https://www.github.com/GGP1/btcs
      - title: Atoll
        content: Cryptographically secure password generator library.
        image: ""
        # featured:
        #   name: Demo
        #   link: demo_url
        badges:
          - "Entropy"
          - "Security"
          - "Library"
          - "Randomness"
        links:
          - icon: fab fa-github
            url: https://www.github.com/GGP1/atoll
      - title: Comeet
        content: Service that keeps track of events from multiple calendar services and accounts, and sends you notifications through different platforms.
        image: ""
        # featured:
        #   name: Demo
        #   link: demo_url
        badges:
          - "Go"
          - "Concurrency"
          - "Event-driven"
          - "Privacy"
        links:
          - icon: fab fa-github
            url: https://www.github.com/GGP1/comeet

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Contact me
    btnLink: mailto:ggpalomeque@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "posts"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/GGP1
      linkedin: https://linkedin.com/gastonpalomeque
      stackoverflow: https://stackoverflow.com/users/12574067/ggp

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: false
    readTime:
      enable: false
      content: "min read"
    scrollprogress:
      enable: false
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
